  CREATE TABLE "MI182_cdrosalita".docu_agree (
	id serial NOT NULL,
	da_date date NULL,
	da_status varchar NULL,
	da_duration int4 NULL,
	franchi_franchi_id int4 NULL,
	franchi_man_id int4 NULL,
	franchi_doc_agree_id int4 NULL,
	franchi_form_id int4 NULL,
	franchi_loc_id int4 NULL,
	fd_id int4 NULL,
	CONSTRAINT docu_agree_pkey PRIMARY KEY (id)
);

CREATE TABLE "MI182_cdrosalita".franchisee (
	id serial NOT NULL,
	fran_fname varchar NULL,
	fran_lname varchar NULL,
	fran_bday date NULL,
	fran_addr varchar NULL,
	fran_sala int4 NULL,
	fran_email varchar NULL,
	fran_num int4 NULL,
	franchi_id int4 NULL,
	manage_id int4 NULL,
	docargee_id int4 NULL,
	form_id int4 NULL,
	location_id int4 NULL,
	fd_id int4 NULL,
	CONSTRAINT franchisee_pkey PRIMARY KEY (id),
	CONSTRAINT franchisee_fk FOREIGN KEY (id) REFERENCES "MI182_cdrosalita".docu_agree(id)
);


insert into "MI182_cdrosalita".docu_agree values
('1',to_date('2019/1/1','yyyy/mm/dd'),'Avtive','1','1','1','1','1','1','1');

insert into "MI182_cdrosalita".docu_agree values
('2',to_date('2019/2/2','yyyy/mm/dd'),'Avtive','2','2','2','2','2','2','2');



insert into "MI182_cdrosalita".franchisee values
('1','Aaron','Realiza',to_date('2019/1/11','yyyy/mm/dd'),'Taguig','11111','AR@gmail.com','1','1','1','1','1','1','1');

insert into "MI182_cdrosalita".franchisee values
('2','Jay','Realize',to_date('2019/2/22','yyyy/mm/dd'),'Makati','22222','JR@gmail.com','2','2','2','2','2','2','2');


CREATE TABLE "MI182_cdrosalita".accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);
 
INSERT INTO accounts(name,balance)
VALUES('Aaron',10000);
 
INSERT INTO accounts(name,balance)
VALUES('Jay',10000);


SELECT * FROM "MI182_cdrosalita".accounts;





CREATE OR REPLACE procedure "MI182_cdrosalita".transfer(INT, INT, DEC)
LANGUAGE plpgsql    
AS $$
BEGIN
    -- subtracting the amount from the sender's account 
    UPDATE accounts 
    SET balance = balance - $3
    WHERE id = $1;
 
    -- adding the amount to the receiver's account
    UPDATE accounts 
    SET balance = balance + $3
    WHERE id = $2;
 
    COMMIT;
END;
$$;

CALL transfer(1,2,1000);
























